---
# tasks file for roles/backup_pki
- name: Create temporary archive of PKI directory
  ansible.builtin.archive:
    path: /etc/kubernetes/pki
    dest: /tmp/pki_backup.tar.gz
    format: gz
  become: true

- name: Fetch PKI archive to local backup directory
  ansible.builtin.fetch:
    src: /tmp/pki_backup.tar.gz
    dest: "{{ local_backup_path }}/pki/pki_backup_{{ ansible_hostname }}.tar.gz"
    flat: yes
  run_once: true

- name: Remove temporary PKI archive from master
  ansible.builtin.file:
    path: /tmp/pki_backup.tar.gz
    state: absent
