---
- name: Download Backup from AWS S3 to Ansible Host
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: download_from_s3

- name: K8s Disaster Recovery - Restore Control Plane Core Data
  hosts: master
  become: yes
  gather_facts: yes
  roles:
    - role: restore_etcd
    - role: restore_pki
    - role: restore_configs

- name: K8s Disaster Recovery - Restore Static Pods & Restart Cluster Nodes
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: restore_static_pods

  post_tasks:
    - name: Final Step - Force Restart Kubelet on all nodes
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes
